# Generated by Django 3.2.9 on 2021-12-04 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0004_picture_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='pictures',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='name',
        ),
        migrations.AddField(
            model_name='picture',
            name='dish',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='restau.dish'),
            preserve_default=False,
        ),
    ]
